taquin: projclav2.o fonction.o
	gcc projclav2.o fonction.o -o taquin -lgraph

projclav2.o: projclav2.c fonction.c
	gcc -c projclav2.c -o projclav2.o -lgraph

fonctions.o: fonction.c fonction.h 
	gcc -c fonction.c -o fonction.o -lgraph